package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class InputOriginInfo_t extends Structure {
	public long devicePath;
	public int trackedDeviceIndex;
	/** char[128] */
	public byte[] rchRenderModelComponentName = new byte[128];
	public InputOriginInfo_t() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("devicePath", "trackedDeviceIndex", "rchRenderModelComponentName");
	}
	public InputOriginInfo_t(long devicePath, int trackedDeviceIndex, byte rchRenderModelComponentName[]) {
		super();
		this.devicePath = devicePath;
		this.trackedDeviceIndex = trackedDeviceIndex;
		if ((rchRenderModelComponentName.length != this.rchRenderModelComponentName.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.rchRenderModelComponentName = rchRenderModelComponentName;
	}
	public InputOriginInfo_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends InputOriginInfo_t implements Structure.ByReference {
		
	};
	public static class ByValue extends InputOriginInfo_t implements Structure.ByValue {
		
	};
}
