package jopenvr;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VR_IVRIOBuffer_FnTable extends Structure {
	public VR_IVRIOBuffer_FnTable.Open_callback Open;
	public VR_IVRIOBuffer_FnTable.Close_callback Close;
	public VR_IVRIOBuffer_FnTable.Read_callback Read;
	public VR_IVRIOBuffer_FnTable.Write_callback Write;
	public VR_IVRIOBuffer_FnTable.PropertyContainer_callback PropertyContainer;
	public VR_IVRIOBuffer_FnTable.HasReaders_callback HasReaders;
	public interface Open_callback extends Callback {
		int apply(Pointer pchPath, int mode, int unElementSize, int unElements, LongByReference pulBuffer);
	};
	public interface Close_callback extends Callback {
		int apply(long ulBuffer);
	};
	public interface Read_callback extends Callback {
		int apply(long ulBuffer, Pointer pDst, int unBytes, IntByReference punRead);
	};
	public interface Write_callback extends Callback {
		int apply(long ulBuffer, Pointer pSrc, int unBytes);
	};
	public interface PropertyContainer_callback extends Callback {
		long apply(long ulBuffer);
	};
	public interface HasReaders_callback extends Callback {
		byte apply(long ulBuffer);
	};
	public VR_IVRIOBuffer_FnTable() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("Open", "Close", "Read", "Write", "PropertyContainer", "HasReaders");
	}
	public VR_IVRIOBuffer_FnTable(VR_IVRIOBuffer_FnTable.Open_callback Open, VR_IVRIOBuffer_FnTable.Close_callback Close, VR_IVRIOBuffer_FnTable.Read_callback Read, VR_IVRIOBuffer_FnTable.Write_callback Write, VR_IVRIOBuffer_FnTable.PropertyContainer_callback PropertyContainer, VR_IVRIOBuffer_FnTable.HasReaders_callback HasReaders) {
		super();
		this.Open = Open;
		this.Close = Close;
		this.Read = Read;
		this.Write = Write;
		this.PropertyContainer = PropertyContainer;
		this.HasReaders = HasReaders;
	}
	public VR_IVRIOBuffer_FnTable(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VR_IVRIOBuffer_FnTable implements Structure.ByReference {
		
	};
	public static class ByValue extends VR_IVRIOBuffer_FnTable implements Structure.ByValue {
		
	};
}
