package jopenvr;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : opencomposite_capi.gen.h:5</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VR_IVROCSystem_FnTable extends Structure {
	// Added manually
	public static final String Version = "FnTable:IVROCSystem_001";

	/** C type : GetExtendedButtonStatus_callback* */
	public VR_IVROCSystem_FnTable.GetExtendedButtonStatus_callback GetExtendedButtonStatus;
	/** <i>native declaration : opencomposite_capi.gen.h:4</i> */
	public interface GetExtendedButtonStatus_callback extends Callback {
		long apply();
	};
	public VR_IVROCSystem_FnTable() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("GetExtendedButtonStatus");
	}
	/** @param GetExtendedButtonStatus C type : GetExtendedButtonStatus_callback* */
	public VR_IVROCSystem_FnTable(VR_IVROCSystem_FnTable.GetExtendedButtonStatus_callback GetExtendedButtonStatus) {
		super();
		this.GetExtendedButtonStatus = GetExtendedButtonStatus;
	}
	public VR_IVROCSystem_FnTable(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VR_IVROCSystem_FnTable implements Structure.ByReference {

	};
	public static class ByValue extends VR_IVROCSystem_FnTable implements Structure.ByValue {

	};
}
