package jopenvr;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VR_IVRTrackedCamera_FnTable extends Structure {
	public VR_IVRTrackedCamera_FnTable.GetCameraErrorNameFromEnum_callback GetCameraErrorNameFromEnum;
	public VR_IVRTrackedCamera_FnTable.HasCamera_callback HasCamera;
	public VR_IVRTrackedCamera_FnTable.GetCameraFrameSize_callback GetCameraFrameSize;
	public VR_IVRTrackedCamera_FnTable.GetCameraIntrinsics_callback GetCameraIntrinsics;
	public VR_IVRTrackedCamera_FnTable.GetCameraProjection_callback GetCameraProjection;
	public VR_IVRTrackedCamera_FnTable.AcquireVideoStreamingService_callback AcquireVideoStreamingService;
	public VR_IVRTrackedCamera_FnTable.ReleaseVideoStreamingService_callback ReleaseVideoStreamingService;
	public VR_IVRTrackedCamera_FnTable.GetVideoStreamFrameBuffer_callback GetVideoStreamFrameBuffer;
	public VR_IVRTrackedCamera_FnTable.GetVideoStreamTextureSize_callback GetVideoStreamTextureSize;
	public VR_IVRTrackedCamera_FnTable.GetVideoStreamTextureD3D11_callback GetVideoStreamTextureD3D11;
	public VR_IVRTrackedCamera_FnTable.GetVideoStreamTextureGL_callback GetVideoStreamTextureGL;
	public VR_IVRTrackedCamera_FnTable.ReleaseVideoStreamTextureGL_callback ReleaseVideoStreamTextureGL;
	public interface GetCameraErrorNameFromEnum_callback extends Callback {
		Pointer apply(int eCameraError);
	};
	public interface HasCamera_callback extends Callback {
		int apply(int nDeviceIndex, Pointer pHasCamera);
	};
	public interface GetCameraFrameSize_callback extends Callback {
		int apply(int nDeviceIndex, int eFrameType, IntByReference pnWidth, IntByReference pnHeight, IntByReference pnFrameBufferSize);
	};
	public interface GetCameraIntrinsics_callback extends Callback {
		int apply(int nDeviceIndex, int nCameraIndex, int eFrameType, HmdVector2_t pFocalLength, HmdVector2_t pCenter);
	};
	public interface GetCameraProjection_callback extends Callback {
		int apply(int nDeviceIndex, int nCameraIndex, int eFrameType, float flZNear, float flZFar, HmdMatrix44_t pProjection);
	};
	public interface AcquireVideoStreamingService_callback extends Callback {
		int apply(int nDeviceIndex, LongByReference pHandle);
	};
	public interface ReleaseVideoStreamingService_callback extends Callback {
		int apply(long hTrackedCamera);
	};
	public interface GetVideoStreamFrameBuffer_callback extends Callback {
		int apply(long hTrackedCamera, int eFrameType, Pointer pFrameBuffer, int nFrameBufferSize, CameraVideoStreamFrameHeader_t pFrameHeader, int nFrameHeaderSize);
	};
	public interface GetVideoStreamTextureSize_callback extends Callback {
		int apply(int nDeviceIndex, int eFrameType, VRTextureBounds_t pTextureBounds, IntByReference pnWidth, IntByReference pnHeight);
	};
	public interface GetVideoStreamTextureD3D11_callback extends Callback {
		int apply(long hTrackedCamera, int eFrameType, Pointer pD3D11DeviceOrResource, PointerByReference ppD3D11ShaderResourceView, CameraVideoStreamFrameHeader_t pFrameHeader, int nFrameHeaderSize);
	};
	public interface GetVideoStreamTextureGL_callback extends Callback {
		int apply(long hTrackedCamera, int eFrameType, IntByReference pglTextureId, CameraVideoStreamFrameHeader_t pFrameHeader, int nFrameHeaderSize);
	};
	public interface ReleaseVideoStreamTextureGL_callback extends Callback {
		int apply(long hTrackedCamera, int glTextureId);
	};
	public VR_IVRTrackedCamera_FnTable() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("GetCameraErrorNameFromEnum", "HasCamera", "GetCameraFrameSize", "GetCameraIntrinsics", "GetCameraProjection", "AcquireVideoStreamingService", "ReleaseVideoStreamingService", "GetVideoStreamFrameBuffer", "GetVideoStreamTextureSize", "GetVideoStreamTextureD3D11", "GetVideoStreamTextureGL", "ReleaseVideoStreamTextureGL");
	}
	public VR_IVRTrackedCamera_FnTable(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VR_IVRTrackedCamera_FnTable implements Structure.ByReference {
		
	};
	public static class ByValue extends VR_IVRTrackedCamera_FnTable implements Structure.ByValue {
		
	};
}
