package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VRActiveActionSet_t extends Structure {
	public long ulActionSet;
	public long ulRestrictedToDevice;
	public long ulSecondaryActionSet;
	public int unPadding;
	public int nPriority;
	public VRActiveActionSet_t() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ulActionSet", "ulRestrictedToDevice", "ulSecondaryActionSet", "unPadding", "nPriority");
	}
	public VRActiveActionSet_t(long ulActionSet, long ulRestrictedToDevice, long ulSecondaryActionSet, int unPadding, int nPriority) {
		super();
		this.ulActionSet = ulActionSet;
		this.ulRestrictedToDevice = ulRestrictedToDevice;
		this.ulSecondaryActionSet = ulSecondaryActionSet;
		this.unPadding = unPadding;
		this.nPriority = nPriority;
	}
	public VRActiveActionSet_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VRActiveActionSet_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VRActiveActionSet_t implements Structure.ByValue {
		
	};
}
