package jopenvr;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VRSkeletalSummaryData_t extends Structure {
	/** float[5] */
	public float[] flFingerCurl = new float[5];
	/** float[4] */
	public float[] flFingerSplay = new float[4];
	public VRSkeletalSummaryData_t() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("flFingerCurl", "flFingerSplay");
	}
	public VRSkeletalSummaryData_t(float flFingerCurl[], float flFingerSplay[]) {
		super();
		if ((flFingerCurl.length != this.flFingerCurl.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.flFingerCurl = flFingerCurl;
		if ((flFingerSplay.length != this.flFingerSplay.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.flFingerSplay = flFingerSplay;
	}
	public VRSkeletalSummaryData_t(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends VRSkeletalSummaryData_t implements Structure.ByReference {
		
	};
	public static class ByValue extends VRSkeletalSummaryData_t implements Structure.ByValue {
		
	};
}
